version: '3'
services:
    file-scanner:
        build:
            context: ./file-scanner
            dockerfile: ./.docker/Dockerfile
        volumes:
            - ./file-scanner:/app
        environment:
            - MINIO_ENDPOINT=${MINIO_ENDPOINT}
            - AWS_BUCKET=${AWS_BUCKET}
        networks:
            - emg-net
    minio:
        image: minio/minio:RELEASE.2022-06-07T00-33-41Z.fips
        command: server --console-address ":9001" /data
        ports:
            - ${MINIO_PORT}:9000
            - ${MINIO_CLIENT_PORT}:9001
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 5s
            timeout: 20s
            retries: 3
        environment:
            MINIO_ACCESS_KEY: ${AWS_KEY:?Provide access key to env}
            MINIO_SECRET_KEY: ${AWS_SECRET:?Provide secret key to env}
        networks:
            - emg-net

networks:
    emg-net:
