version: '3.5'

services:
  emg-app:
    container_name: emg-app
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    volumes:
      - ./:/var/www
    restart: always
    depends_on:
      - emg-db
    command: "/var/server/rr serve"
    networks:
      - emg-net

  emg-db:
    image: postgres:14.3-alpine3.15
    container_name: emg-db
    ports:
      - ${DB_PORT}:${DB_SOURCE_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    networks:
      - emg-net

  emg-nginx:
    container_name: emg-nginx
    depends_on:
      - emg-app
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/share/nginx/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    command: "./wait-for-it.sh php:8080 -- nginx -g 'daemon off;'"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-http.entrypoints=web
      - traefik.http.routers.nginx-http.rule=Host(`emigraniada.localhost`)
      - traefik.http.routers.nginx-http.middlewares=nginx-https
      - traefik.http.middlewares.nginx-https.redirectscheme.scheme=https
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`emigraniada.localhost`)
      - traefik.http.routers.nginx.tls=true
    networks:
      - emg-net

  reverse-proxy:
    container_name: emg-traefik
    image: traefik:v2.6
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/configuration:/configuration/
      - ./docker/traefik/certs:/etc/certs:ro
    networks:
      - emg-net

networks:
  emg-net:
